from typing import Any

class Tensor: ...

class device:
    def __init__(self, type: str): ...

def no_grad() -> Any: ...
def save(obj: Any, f: str) -> None: ...
def load(f: str, map_location: Any = ...) -> Any: ...
