from typing import Any

from torch import Tensor

class Module:
    def eval(self) -> None: ...
    def state_dict(self) -> Any: ...
    def load_state_dict(self, state: Any) -> None: ...

class Embedding(Module):
    num_embeddings: int
    embedding_dim: int
    def __init__(self, num_embeddings: int, embedding_dim: int, padding_idx: int | None = ...) -> None: ...

class LSTM(Module):
    hidden_size: int
    num_layers: int
    bidirectional: bool
    def __init__(self, input_size: int, hidden_size: int, num_layers: int = ..., bidirectional: bool = ..., batch_first: bool = ..., dropout: float = ...) -> None: ...
    def __call__(self, x: Tensor) -> tuple[Tensor, tuple[Tensor, Tensor]]: ...

class Linear(Module):
    out_features: int
    def __init__(self, in_features: int, out_features: int) -> None: ...
    def __call__(self, x: Tensor) -> Tensor: ...

class Dropout(Module):
    p: float
    def __init__(self, p: float = ...) -> None: ...
    def __call__(self, x: Tensor) -> Tensor: ...
