from typing import Any

class Engine: ...

def create_engine(url: str, connect_args: dict[str, Any] | None = ...) -> Engine: ...

class Boolean: ...
class DateTime: ...
class Integer: ...
class String:
    def __init__(self, length: int | None = ...) -> None: ...
class Text: ...
