from typing import Any, Generic, TypeVar

class DeclarativeBase: ...

T = TypeVar("T")

class Mapped(Generic[T]): ...

def mapped_column(*args: Any, **kwargs: Any) -> Any: ...

class Session:
    def add(self, obj: Any) -> None: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...
    def query(self, model: Any) -> Any: ...

def sessionmaker(bind: Any) -> Any: ...
